services:
  api:
    container_name: api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=admin
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=example
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"
  db:
    container_name: db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=example
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
volumes:
  dbdata:
networks:
  default:
    name: api